version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rhaxod0820
      MYSQL_DATABASE: palink
      MYSQL_USER: palink_user
      MYSQL_PASSWORD: rhaxod0820
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
